# Generated by Django 3.2.16 on 2023-03-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_animate_on_scroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animateonscroll_element',
            name='aos_delay',
            field=models.IntegerField(blank=True, help_text='Delay animation (ms)', null=True, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='animateonscroll_element',
            name='aos_duration',
            field=models.IntegerField(blank=True, help_text='Duration of animation (ms)', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='animateonscroll_element',
            name='aos_offset',
            field=models.IntegerField(blank=True, help_text='Change offset to trigger animations sooner or later (px)', null=True, verbose_name='Offset'),
        ),
    ]
