# Generated by Django 3.2.16 on 2023-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_animate_on_scroll', '0002_auto_20230302_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateonscroll_element',
            name='aos_mirror',
            field=models.BooleanField(help_text='Choose whether the elements should animate in reverse when they leave the screen', null=True, verbose_name='Mirror'),
        ),
    ]
