repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: "migrations/"
        types: [python]

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        exclude: "migrations/"
        types: [python]
        args: ["--config", "pyproject.toml"]
